version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata 
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data: